language: csharp
solution: src/Nancy.sln
sudo: false
install:
  - gem install bundle
  - bundle
  - echo \#\!/bin/bash >> ./travis.sh
  - echo set -e >> ./travis.sh
  - echo set -x >> ./travis.sh
  - echo set -o pipefail >> ./travis.sh
  - echo echo Running on latest Mono >> ./travis.sh
  - echo rake mono >> ./travis.sh
  - chmod +x ./travis.sh
  - cat travis.sh
script: ./travis.sh
notifications:
  email:
    - nancy@nancyfx.org
gemfile: Gemfile
