language: ruby
rvm:
  - 1.9.3
install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs mono-vbnc
  - gem install bundle
  - bundle
  - echo \#\!/bin/bash >> ./travis.sh
  - echo set -e >> ./travis.sh
  - echo set -x >> ./travis.sh
  - echo set -o pipefail >> ./travis.sh
  - echo echo Running on Mono 3.x >> ./travis.sh
  - echo rake mono >> ./travis.sh
  - chmod +x ./travis.sh
  - cat travis.sh
script: ./travis.sh
notifications:
  email:
    - nancy@nancyfx.org
gemfile: Gemfile
